// pipeline {
//     agent any

//     environment {
//         IMAGE_NAME = "flumpland-app"
//         CONTAINER_NAME = "flumpland-app-container"
//     }

//     stages {

//         stage('Checkout') {
//             steps {
//                 checkout scm
//             }
//         }

//         stage('Build Application') {
//             steps {
//                 dir('API') {
//                     sh 'chmod +x mvnw'
//                     sh './mvnw clean package -DskipTests'
//                 }
//             }
//         }

//         stage('Verify Build') {
//             steps {
//                 dir('API') {
//                     sh 'ls -lh target'
//                 }
//             }
//         }

//         stage('Build Docker Image') {
//             steps {
//                 dir('API') {
//                     sh 'docker build -t ${IMAGE_NAME}:latest .'
//                 }
//             }
//         }

//         stage('Stop Old Container') {
//             steps {
//                 sh 'docker rm -f ${CONTAINER_NAME} || true'
//             }
//         }

//         stage('Run Container') {
//             steps {
//                 sh '''
//                 docker run -d \
//                 --name ${CONTAINER_NAME} \
//                 -p 9091:9091 \
//                 ${IMAGE_NAME}:latest
//                 '''
//             }
//         }

//         stage('Health Check') {
//             steps {
//                 sh 'sleep 20'
//                 sh 'docker ps'
//             }
//         }
//     }

//     post {
//         success {
//             echo 'Application deployed successfully.'
//         }

//         failure {
//             echo 'Deployment failed.'
//         }
//     }
// }

pipeline {

    agent any

    environment {

        IMAGE_NAME = "flumpland-app"

    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('API') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {

            steps {

                dir('API') {

                    sh 'docker build -t ${IMAGE_NAME}:latest .'

                }

            }

        }

        stage('Deploy Kubernetes') {

            steps {

                dir('API') {

                    sh '''
                    kubectl apply -f k8s/namespace.yaml

                    kubectl apply -f k8s/deployment.yaml

                    kubectl apply -f k8s/service.yaml
                    '''

                }

            }

        }

        stage('Verify') {

            steps {

                sh 'kubectl get pods -n flumpland'

                sh 'kubectl get deployment -n flumpland'

                sh 'kubectl get svc -n flumpland'

            }

        }

    }

}